name: Run IO tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Build
        run: make main

      - name: Run Tests
        run: make test

      - name: Cleanup
        run: make clean